### ISSUE TITLE
Cannot build

### ISSUE THREAD

**Issue by hy9be** [terrychou/ivish#1]
Hey, I was trying to build your iVim project (nice work btw). The dependency directed me to here. But I cannot build this project as ``ios_getSession`` and ``sessionParameters`` are both not defined in the holzschu's ios_system framework. Could you please shed some lights here? Thanks!

**Comment by terrychou** [comment]
I made some small changes to the ios_system to adapt it to ivish. If you just want to build iVim, you can use the pre-compiled frameworks as discussed in this issue: https://github.com/terrychou/iVim/issues/109

**Comment by hy9be** [comment]
Ah, I see. Thank you!
